// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Traces",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Traces",
            targets: ["AppModule"],
            bundleIdentifier: "com.astro.Traces",
            teamIdentifier: "XH89Z8J7P5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            appCategory: .education
        )
    ],
    dependencies: [
        .package(url: "https://github.com/Mijick/Popups", "4.0.1"..<"5.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "MijickPopups", package: "popups")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)